### PR TITLE
Updating JAR to be OSGi compatible

### PR DESCRIPTION
**Pull request by bocon13**
Adding the maven-bundle-plugin to the build, which will add the required headers to the manifest enabling the jar to be loaded as an OSGi bundle.

### CODE REVIEW

**Comment by npgall** [comment]
Hi Brian,

As someone not familiar with OSGi, this seems quite an invasive pull request, as it changes the packing of this entire library.

This library is already single jar with no transitive dependencies. Does OSGi really require that every library is repackaged?

Are there any downsides for non-OSGi users? Is this packaging 100% backward compatible with older versions of Maven? What kind of problems does it cause for OSGi users when this library does not have OSGi packaging?

That said, I'm not opposed to making improvements to suit OSGi systems as long as it will not cause problems for non-OSGi systems.

Thanks,
Niall

**Comment by bocon13** [comment]
Hi Niall,

Thanks for your reply!

There are no changes to the structure of the jar and no additional files added. To make a jar OSGi-compliant, all that needs to be done is to add some headers to the jar's manifest.

The existing jar's manifest is as follows:
`Archiver-Version                         Plexus Archiver                         
Build-Jdk                                1.8.0_73                                
Built-By                                 bocon                                   
Created-By                               Apache Maven 3.3.1                      
Manifest-Version                         1.0                                     
`

As a bundle, here is the jar's manifest:
`Bnd-LastModified                         1464071670868                           
Build-Jdk                                1.8.0_73                                
Built-By                                 bocon                                   
Bundle-Description                       Concurrent Radix Trees and Concurrent Suffix Trees for Java.
Bundle-License                           http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion                   2                                       
Bundle-Name                              Concurrent-Trees                        
Bundle-SymbolicName                      com.googlecode.concurrent-trees         
Bundle-Version                           2.5.1.SNAPSHOT                          
Created-By                               Apache Maven Bundle Plugin              
Export-Package                           com.googlecode.concurrenttrees.common;uses:="com.googlecode.concurrenttrees.radix.node.util";version="2.5.1",com.googlecode.concurrenttrees.radix;uses:="com.googlecode.concurrenttrees.common,com.googlecode.concurrenttrees.radix.node,com.googlecode.concurrenttrees.radix.node.util";version="2.5.1",com.googlecode.concurrenttrees.radix.node.concrete.bytearray;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.radix.node.concrete.chararray;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.radix.node.concrete.charsequence;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.radix.node.concrete;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.radix.node.concrete.voidvalue;version="2.5.1",com.googlecode.concurrenttrees.radix.node;uses:="com.googlecode.concurrenttrees.radix.node.util";version="2.5.1",com.googlecode.concurrenttrees.radix.node.util;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.radixinverted;uses:="com.googlecode.concurrenttrees.common,com.googlecode.concurrenttrees.radix,com.googlecode.concurrenttrees.radix.node,com.googlecode.concurrenttrees.radix.node.util";version="2.5.1",com.googlecode.concurrenttrees.radixreversed;uses:="com.googlecode.concurrenttrees.common,com.googlecode.concurrenttrees.radix.node,com.googlecode.concurrenttrees.radix.node.util";version="2.5.1",com.googlecode.concurrenttrees.solver;uses:="com.googlecode.concurrenttrees.radix.node";version="2.5.1",com.googlecode.concurrenttrees.suffix;uses:="com.googlecode.concurrenttrees.common,com.googlecode.concurrenttrees.radix.node,com.googlecode.concurrenttrees.radix.node.util";version="2.5.1"
Import-Package                           com.googlecode.concurrenttrees.common,com.googlecode.concurrenttrees.radix,com.googlecode.concurrenttrees.radix.node,com.googlecode.concurrenttrees.radix.node.concrete.bytearray,com.googlecode.concurrenttrees.radix.node.concrete.chararray,com.googlecode.concurrenttrees.radix.node.concrete.charsequence,com.googlecode.concurrenttrees.radix.node.concrete.voidvalue,com.googlecode.concurrenttrees.radix.node.util
Manifest-Version                         1.0                                     
Require-Capability                       osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Tool                                     Bnd-3.0.0.201509101326                  
`

The key properties are: Bundle-SymbolicName, Bundle-Version, Import-Package, and Export-Package. These are ignored by the plain JVM, but are required and interpreted by an OSGi implementation.

For non-OSGi users, the only downside is that the jar is 4KB larger (which seems fairly trivial to me). 

For OSGi users, they need to repackage or wrap the jar to provide the properties described above. This process is more-or-less straightforward because there are no external dependencies, but it is an inconvenient step.

For users who want to build the library from source, I am not sure what the required version of Maven is, but the maven-bundle-plugin dates back to 2008, so we could use an older version if required.

For those who want to use the library via the Maven coordinates, there is no difference between "jar" and "bundle" as both are really just jars, and the user will not notice a difference.

I hope this addresses your questions, and I would be happy to clarify or provide more details.

Brian

**Comment by npgall** [comment]
Hi Brian,

That sounds absolutely fine. I appreciate the details - and of course the Pull Request! I will merge it now, and this will be included in the next release. I will make a release to include this soon.

Many thanks!
Niall

**Comment by bocon13** [comment]
Great! Thanks, Niall!

**Pull request merged**
